main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.std_login, name='std_login'),
    path('my/', views.mySpaces, name='mySpaces'),
    path('leaderSpaces/', views.leaderSpaces, name='leaderSpaces'),
    path('login/', views.std_login, name='std_login'),
    path('logout/', views.std_logout, name='std_logout'),
    path('my/<int:code>/', views.space_page, name='space'),
    path('profile/<str:id>/', views.profile, name='profile'),
    path('leaderProfile/<str:id>/', views.profile, name='profile_leader'),
    path('leader/<int:code>/', views.space_page_leader, name='leader'),
    path('addAnnouncement/<int:code>/',
         views.addAnnouncement, name='addAnnouncement'),
    path('announecement/<int:code>/<int:id>/',
         views.deleteAnnouncement, name='deleteAnnouncement'),
    path('edit/<int:code>/<int:id>/',
         views.editAnnouncement, name='editAnnouncement'),
    path('update/<int:code>/<int:id>/',
         views.updateAnnouncement, name='updateAnnouncement'),
    path('addReport/<int:code>/', views.addReport, name='addReport'),
    path('report/<int:code>/<int:id>/',
         views.reportPage, name='reportPage'),
    path('reports/<int:code>/', views.allReports, name='allReports'),
    path('member-reports/<int:code>/',
         views.allReportsSTD, name='member-reports'),
    path('addSubmission/<int:code>/<int:id>/',
         views.addSubmission, name='addSubmission'),
    path('submission/<int:code>/<int:id>/',
         views.viewSubmission, name='submission'),
    path('gradeSubmission/<int:code>/<int:id>/<int:sub_id>',
         views.gradeSubmission, name='gradeSubmission'),
    path('space-coupon/<int:code>/',
         views.addSpaceCoupon, name='addSpaceCoupon'),
    path('space-coupon/<int:code>/<int:id>/',
         views.deleteSpaceCoupon, name='deleteSpaceCoupon'),
    path('spaces/', views.spaces, name='spaces'),
    path('branches/', views.branches, name='branches'),
    path('access/<int:code>/', views.access, name='access'),
    path('changePasswordPrompt/', views.changePasswordPrompt,
         name='changePasswordPrompt'),
    path('changePhotoPrompt/', views.changePhotoPrompt, name='changePhotoPrompt'),
    path('changePassword/', views.changePassword, name='changePassword'),
    path('changePasswordLeader/', views.changePasswordLeader,
         name='changePasswordLeader'),
    path('changePhoto/', views.changePhoto, name='changePhoto'),
    path('changePhotoLeader/', views.changePhotoLeader,
         name='changePhotoLeader'),
    path('search/', views.search, name='search'),
    path('error/', views.error, name='error'),
]

pobail/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from main import views


admin.site.site_header = "Pobail Administration"
admin.site.site_title = "Pobail Administration Portal"
admin.site.index_title = "Welcome to Pobail Administration Portal"


urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('member/', views.guestMember, name='guestMember'),
    path('leader/', views.guestLeader, name='guestLeader'),
    path('', include('main.urls')),
    path('', include('talk.urls')),
    path('', include('attendance.urls')),
    path('', include('quiz.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
# Create your models here.


class Member(models.Model):
    member_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=255, null=False)
    role = models.CharField(
        default="Member", max_length=100, null=False, blank=True)
    space = models.ManyToManyField(
        'Space', related_name='members', blank=True)
    photo = models.ImageField(upload_to='profile_pics', blank=True,
                              null=False, default='profile_pics/default_member.png')
    branch = models.ForeignKey(
        'Branch', on_delete=models.CASCADE, null=False, blank=False, related_name='members')

    def delete(self, *args, **kwargs):
        if self.photo != 'profile_pics/default_member.png':
            self.photo.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Members'

    def __str__(self):
        return self.name


class Leader(models.Model):
    leader_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    email = models.EmailField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=255, null=False)
    branch = models.ForeignKey(
        'Branch', on_delete=models.CASCADE, null=False, related_name='leader')
    role = models.CharField(
        default="Leader", max_length=100, null=False, blank=True)
    photo = models.ImageField(upload_to='profile_pics', blank=True,
                              null=False, default='profile_pics/default_leader.png')

    def delete(self, *args, **kwargs):
        if self.photo != 'profile_pics/default_leader.png':
            self.photo.delete()
        super().delete(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Leader'

    def __str__(self):
        return self.name


class Branch(models.Model):
    branch_id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=100, null=False)
    description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Branches'

    def __str__(self):
        return self.name

    def member_count(self):
        return self.members.count()

    def leader_count(self):
        return self.leader.count()

    def space_count(self):
        return self.spaces.count()


class Space(models.Model):
    code = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=255, null=False, unique=True)
    branch = models.ForeignKey(
        Branch, on_delete=models.CASCADE, null=False, related_name='spaces')
    leader = models.ForeignKey(
        Leader, on_delete=models.SET_NULL, null=True, blank=True)
    memberKey = models.IntegerField(null=False, unique=True)
    leaderKey = models.IntegerField(null=False, unique=True)

    class Meta:
        unique_together = ('code', 'branch', 'name')
        verbose_name_plural = "Spaces"

    def __str__(self):
        return self.name


class Announcement(models.Model):
    space_code = models.ForeignKey(
        Space, on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=255, null=False)
    description = models.TextField(max_length=2000, null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    file = models.FileField(upload_to='announcement_files', blank=True, null=True)

    class Meta:
        verbose_name_plural = "Announcements"
        ordering = ['-datetime']

    def __str__(self):
        return self.title

    def post_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")


class Report(models.Model):
    space_code = models.ForeignKey(
        Space, on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=255, null=False)
    description = models.TextField(max_length=2000, null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    deadline = models.DateTimeField(null=False)
    file = models.FileField(upload_to='reports/', null=True, blank=True)
    marks = models.DecimalField(max_digits=6, decimal_places=2, null=False)

    class Meta:
        verbose_name_plural = "Reports"
        ordering = ['-datetime']

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def post_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

    def due_date(self):
        return self.deadline.strftime("%d-%b-%y, %I:%M %p")


class Submission(models.Model):
    report = models.ForeignKey(
        Report, on_delete=models.CASCADE, null=False)
    member = models.ForeignKey(Member, on_delete=models.CASCADE, null=False)
    file = models.FileField(upload_to='submissions/', null=True,)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    marks = models.DecimalField(
        max_digits=6, decimal_places=2, null=True, blank=True)
    status = models.CharField(max_length=100, null=True, blank=True)

    def file_name(self):
        return self.file.name.split('/')[-1]

    def time_difference(self):
        difference = self.report.deadline - self.datetime
        days = difference.days
        hours = difference.seconds//3600
        minutes = (difference.seconds//60) % 60
        seconds = difference.seconds % 60

        if days == 0:
            if hours == 0:
                if minutes == 0:
                    return str(seconds) + " seconds"
                else:
                    return str(minutes) + " minutes " + str(seconds) + " seconds"
            else:
                return str(hours) + " hours " + str(minutes) + " minutes " + str(seconds) + " seconds"
        else:
            return str(days) + " days " + str(hours) + " hours " + str(minutes) + " minutes " + str(seconds) + " seconds"

    def submission_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.member.name + " - " + self.report.title

    class Meta:
        unique_together = ('report', 'member')
        verbose_name_plural = "Submissions"
        ordering = ['datetime']


class Coupon(models.Model):
    space_code = models.ForeignKey(
        Space, on_delete=models.CASCADE, null=False)
    title = models.CharField(max_length=255, null=False)
    description = models.TextField(max_length=2000, null=False)
    datetime = models.DateTimeField(auto_now_add=True, null=False)
    file = models.FileField(upload_to='coupons/', null=True, blank=True)

    class Meta:
        verbose_name_plural = "Coupons"
        ordering = ['-datetime']

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        self.file.delete()
        super().delete(*args, **kwargs)

    def post_date(self):
        return self.datetime.strftime("%d-%b-%y, %I:%M %p")

main/templates/main/access.html
{% extends 'index.html' %}
{% block title %} {{ space.name }} | Pobail {% endblock title %}
{% block profile %}
{% url 'profile' member.member_id %}
{% endblock %}
{% block user %}
{{member.name}}
{% endblock user %}
{% block allSpaces %}
{% url 'spaces' %}
{% endblock%}
{% block spaces %}
{% url 'mySpaces' %}
{% endblock %}
{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger alert-dismissible fade show text-center" role="alert">
   <span> {{ message }}</span>
   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}


<div class="container-fluid d-flex" style="min-height: 70vh;">
   <div class="row justify-content-center m-3 align-self-center w-100">
      <div class="col-lg-4 col-sm-12 col-md-6 border p-3 rounded">
         <form action="" method="post">
            {% csrf_token %}
            <div class="mb-3">
               <label for="key" class="form-label">Enter the access key: </label>
               <input type="number" class="form-control" id="key" name="key" min="0" placeholder="e.g. 1234">
            </div>
            <button type="submit" class="btn btn-sm btn-primary">Submit</button>
         </form>
      </div>
   </div>
</div>
{% endblock %}

main/templates/main/all-reports-std.html
{% extends 'index.html' %}
{% load static %}
{% block title %}Reports | {{ space.name }} | Pobail {% endblock title %}
{% block profile %}
{% url 'profile' member.member_id %}
{% endblock %}
{% block user %}
{{member.name}}
{% endblock user %}
{% block spaces %}
{% url 'mySpaces' %}
{% endblock spaces %}
{% block allSpaces %}
{% url 'spaces' %}
{% endblock allSpaces %}
{% block content %}
<div>
   <!-- navigation links -->
   <div class="container shadow-sm">
      <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item"><a style="color: rgb(59, 31, 18)" href="{% url 'mySpaces' %}">My
               Spaces</a>
            </li>
            <li class="breadcrumb-item"><a style="color: rgb(59, 31, 18)"
               href="{% url 'space' space.code %}">{{ space.name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Report</li>
         </ol>
      </nav>
   </div>
   <!-- navigation links end -->
   <div class="container d-flex flex-wrap flex-column">
      <!-- space name starts -->
      <div class="space-section p-3 m-3 shadow-sm d-flex justify-content-center">
         <div class="fs-5 space_name">{{space.branch}}-{{space.code}} : {{space.name}}</div>
      </div>
      <!-- space name ends -->
      <!-- report section starts -->
      <div class="space-section p-3 m-3 shadow">
         <h4 style="color: rgb(59, 31, 18);"><img src="{% static 'images/icon/open-book.png' %}"
            alt="" style="height:1.5rem"><span style="margin-right: 0.6rem;"></span>Report</h4>
         <div>
            {% for report in reports %}
            <!-- individual report starts -->
            <a class="fs-6"
               href="{% url 'reportPage' space.code report.id %}">{{report.title}}</a>
            <div class="fs-6 text-muted border-bottom d-flex justify-content-between">
               <div>
                  {{report.post_date}}
               </div>
               <p> Due Date : {{ report.due_date}} </p>
            </div>
            <!-- individual report ends -->
            {% empty %}
            <h6 style="text-align:center">No reports given yet</h6>
            {% endfor %}
         </div>
         <div class="text-center fs-6 mt-3">
            <p>Showing {{ reports.count}} of {{space.report_set.count}} {% if reports.count == 1 %}report {% else %}reports{% endif %}</p>
         </div>
      </div>
      <!-- report section ends -->
   </div>
</div>
{% endblock %}

main/templates/main/all-reports.html
{% extends 'index.html' %}
{% load static %}
{% block title %} Reports | {{ space.name }} | Pobail {% endblock title %}
{% block profile %}
{% url 'profile' leader.leader_id %}
{% endblock %}
{% block user %}
{{leader.name}}
{% endblock user %}
{% block spaces %}
{% url 'leaderSpaces' %}
{% endblock spaces %}
{% block allSpaces %}
{% url 'spaces' %}
{% endblock %}
{% block content %}
<div>
   <!-- navigation links -->
   <div class="container shadow-sm">
      <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item"><a style="color: rgb(59, 31, 18)"
               href="{% url 'leaderSpaces' %}">My
               Spaces</a>
            </li>
            <li class="breadcrumb-item"><a style="color: rgb(59, 31, 18)"
               href="{% url 'leader' space.code %}">{{ space.name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Report</li>
         </ol>
      </nav>
   </div>
   <!-- navigation links end -->
   <div class="container d-flex flex-wrap flex-column">
      <!-- space name starts -->
      <div class="space-section p-3 m-3 shadow-sm d-flex justify-content-center">
         <div class="fs-5 space_name">{{space.branch}}-{{space.code}} : {{space.name}}</div>
      </div>
      <!-- space name ends -->
      <!-- report section starts -->
      <div class="space-section p-3 m-3 shadow">
         <div class="d-flex flex-row justify-content-between edit">
            <h4 style="color: rgb(59, 31, 18);"><img src="{% static 'images/icon/open-book.png' %}"
               alt="" style="height:1.5rem"><span style="margin-right: 0.6rem;"></span>Report</h4>
            <a style="height:2rem"
               href="{% url 'addReport' space.code %}">
            <img src="{% static 'images/icon/iconBlack.png' %}"
               alt="" height="32">
            </a>
         </div>
         <div class="add-announcement">
            {% for report in reports %}
            <!-- individual report starts --> 
            <a class="text-bold fs-5" href="{% url 'submission' space.code report.id %}">
            {{report.title}}</a>
            <div class="d-flex justify-content-between align-items-center">
               <p style="margin-bottom:0;" class="text-muted">Submitted : {{ report.submission_set.count}} / {{ memberCount }} </p>
               <p class="fs-6 text-muted" style="margin-bottom:0;">
                  {{report.datetime}}
               </p>
            </div>
            <p style="margin-bottom:0;">Submission ends : {{ report.deadline }}</p>
            <hr>
            <!-- individual report ends -->
            {% empty %}
            <h6 style="text-align:center">No reports given yet</h6>
            {% endfor %}
         </div>
         <div class="text-center fs-6">
            <p>Showing {{ reports.count}} of {{space.report_set.count}} {% if reports.count == 1 %}report {% else %}reports{% endif %}</p>
         </div>
      </div>
      <!-- report section ends -->
   </div>
</div>
{% endblock %}

main/templates/main/space.html
{% extends 'index.html' %}
{% load static %}
{% block title %} {{ space.name }} | Pobail {% endblock title %}
{% block profile %}
{% url 'profile' member.member_id %}
{% endblock %}
{% block user %}
{{member.name}}
{% endblock user %}
{% block spaces %}
{% url 'mySpaces' %}
{% endblock spaces %}
{% block allSpaces %}
{% url 'spaces' %}
{% endblock allSpaces %}
{% block content %}
<div>
   <!-- navigation links -->
   <div class="container shadow-sm">
      <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='currentColor'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb">
         <ol class="breadcrumb p-3">
            <li class="breadcrumb-item"><a style="color: rgb(59, 31, 18)" href="{% url 'mySpaces' %}">My
               Spaces</a>
            </li>
            <li class="breadcrumb-item"><a class="breadcrumb-item active"
               aria-current="page">{{ space.name }}</a></li>
         </ol>
      </nav>
   </div>
   <!-- navigation links end -->
   <div class="container d-flex flex-wrap flex-column">
      <div class="row">
      <!-- space name starts -->
      <div class="col-sm-6 p-3">
         <div class="rounded p-3 shadow d-flex justify-content-between">
         <span></span>
         <h5 class="mt-2">{{space.branch}}-{{space.code}} : {{space.name}}</h5>
         <div class="dropdown">
            <img class="dropdown-toggle" id="drop" data-bs-toggle="dropdown" aria-expanded="false" src="{% static 'images/icon/dropDown.png' %}"
               alt="Options" height="32">
            <ul class="dropdown-menu">
               <li class="border-bottom">
                  <a class="dropdown-item" href="{% url 'talk' space.code %}">
                     <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-right-dots mx-2" viewBox="0 0 16 16">
                        <path d="M2 1a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h9.586a2 2 0 0 1 1.414.586l2 2V2a1 1 0 0 0-1-1H2zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"/>
                        <path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                     </svg>
                     Talk
                  </a>
               </li>
               <li>
                  <a class="dropdown-item" href="{% url 'myQuizzes' space.code %}">
                     <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-card-text mx-2" viewBox="0 0 16 16">
                        <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
                        <path d="M3 5.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 8zm0 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z"/>
                     </svg>
                     Quiz
                  </a>
               </li>
            </ul>
         </div>
      </div>
      </div>
      <!-- space name ends -->
      <!-- announcement section starts -->
      <div class="col-sm-6 p-3">
      <div class="rounded p-3 shadow border border-top-0 border-end-0 border-bottom-0 border-primary border-5">
         <div class="Down fs-5 text-center border-bottom border-1 mb-2 py-2" style="color: rgb(59, 31, 18);"><img src="{% static 'images/icon/megaphone.png' %}"
            alt="" style="height:1.5rem;vertical-align: text-top"><span style="margin-right: 0.6rem;"></span>Announcement
         </div>
         <div>
            {% for announcement in announcements %}
            <!-- individual announcement starts -->
            <h6>{{announcement.title}}</h6>
            <div class="fs-6 text-break opacity-75" id="annDescription{{announcement.id}}">{{announcement.description}}</div>
            {% if announcement.file %}
            <div id="annUrl{{announcement.id}}">{{announcement.file.url}}</div>
            {% else %}
            <div id="annUrl{{announcement.id}}">No files</div>
            {% endif %}
            <div class="d-flex flex-row-reverse">
               <div  style="color:grey;">
                  {{announcement.post_date}}
               </div>
            </div>
            <!-- individual announcement ends-->
            {% empty %}
            <p class="fs-6 text-center text-muted">No announcement has been posted</p>
            {% endfor %}
         </div>
      </div>
      </div>
      <!-- announcement section ends -->
      <!-- report section starts -->
      <div class="col-sm-6 p-3">
      <div class="rounded p-3 shadow border border-top-0 border-bottom-0 border-end-0 border-danger border-5 mb-2">
         <div class="fs-5 text-center Down border-bottom border-1 mb-2 py-2" style="color: rgb(59, 31, 18);"><img src="{% static 'images/icon/open-book.png' %}"
            alt="" style="height:1.5rem; vertical-align: text-top"><span style="margin-right: 0.6rem;"></span>Report</div>
         <div >
            {% for report in reports %}
            <!-- individual report starts -->
            <a
               href="{% url 'reportPage' space.code report.id %}">{{report.title}}</a>
            <div class="d-flex justify-content-between">
               <p style="font-size:15px"> Due Date : {{ report.due_date}} </p>
               <div  style="color:grey;">
                  {{report.post_date}}
               </div>
            </div>
            <!-- individual report ends -->
            {% empty %}
            <p class="text-center text-muted fs-6">No reports given yet</p>
            {% endfor %}
         </div>
         {% if reports %}
         <div class="text-center fs-6 text-muted d-flex flex-column border-top border-1">
            <span class="mt-2">Showing {{ reports.count}} of {{space.report_set.count}}
            {% if reports.count == 1 %}report {% else %}reports{% endif %}
            </span>
            <a class="fs-6" href=" {% url 'member-reports' space.code %} ">Show all</a>
         </div>
         {% endif %}
      </div>
      </div>
      <!-- report section ends -->
      <!-- space coupon section starts -->
      <div class="col-sm-6 p-3">
      <div class="rounded p-3 shadow border border-top-0 border-bottom-0 border-warning border-end-0 border-5" id="coupon">
         <!-- section title -->
         <div class="Down fs-5 text-center border-bottom border-1 mb-2 py-2" style="color: rgb(59, 31, 18);"><img src="{% static 'images/icon/coupon.png' %}"
            alt="" style="height:1.5rem;vertical-align: text-top"><span style="margin-right: 0.6rem;"></span>Space Coupon</div>
         <!-- section title ends -->
         <div>
            {% for coupon in coupons  %}
            <!-- individual coupon starts -->
            <a  href="{{ coupon.file.url }}">{{coupon.title}}</a><br>
            <div class="d-flex justify-content-between text-break">
               <p>{{ coupon.description }}</p>
               <div  style="color:grey;">
                  {{coupon.post_date}}
               </div>
            </div>
            {% empty %}
            <p class="text-center text-muted fs-6">Space coupons not available</p>
            {% endfor %}
            <!-- individual coupon ends -->
         </div>
      </div>
      </div>
      <!-- space coupon section ends -->
      </div>
   </div>
</div>

<script>
   let annDescription = []
   let annUrl = []
   {% for announcement in announcements %}
   annDescription.push(document.getElementById(`annDescription{{announcement.id}}`))
   {% if announcement.file %}
   annUrl.push(document.getElementById(`annUrl{{announcement.id}}`))
   {% endif %}
  {% endfor %}
   annDescription.forEach(function (element) {
      if (element.innerHTML.includes("https://") || element.innerHTML.includes("http://")) {
         element.innerHTML = element.innerHTML.replace(/(https?:\/\/[^\s]+)/g, '<a href="$1" target="_blank">$1</a>');
      }
   })
   annDescription.forEach(function (element,index) {
      if (element.innerHTML.includes("{file}")) {
         //remove coupon name from url
         let url = annUrl[index].innerHTML
         let urlArr = url.split("/")
         let fileName = urlArr[urlArr.length-1]
         element.innerHTML = element.innerHTML.replace("{file}", `<a href="${url}" target="_blank">${fileName}</a>`);
         annUrl[index].style.display = "none"
      }
      else
         {
         annUrl[index].style.display = "none"
         }
   })
</script>
{% endblock %}